Add gvar and gvar usage
mjc4wilton/BackpackOnChestRedux pull request #13
Opened 2024-05-17 18:53 UTC by some-evil-kitty

**When merged this pull request will:**
- Add a new GVAR VarBlacklist for exceptions to variable transfer
- Useful if a pfh handle being nil is used to detect presence of pfh on backpackContainer

2024-05-17 19:38 UTC, rautamiekka requested changes

2024-05-17 19:38 UTC, rautamiekka commented on addons/main/functions/fnc_actionSwap.sqf
> +} forEach } forEach ((allVariables (backpackContainer _unit) - GVAR(VarBlacklist)));
That's a funny mistake.
```suggestion
} forEach ((allVariables (backpackContainer _unit) - GVAR(VarBlacklist)));
```

2024-05-17 19:39 UTC, some-evil-kitty commented
Real and true, very funny lmao

2024-05-22 14:37 UTC, rautamiekka approved these changes

2024-05-22 22:44 UTC, merged

2024-05-22 22:44 UTC, mjc4wilton commented
build failed due to HEMTT not ignoring `initSettings.sqf` correctly. Merging and dealing with directly in main